ALTER TABLE `party` ADD FOREIGN KEY (`type`) REFERENCES `partyType` (`code`) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE `party` ADD FOREIGN KEY (`company`) REFERENCES `company` (`id`) ON UPDATE SET NULL ON DELETE SET NULL;

ALTER TABLE `party` ADD FOREIGN KEY (`person`) REFERENCES `person` (`id`) ON UPDATE SET NULL ON DELETE SET NULL;

ALTER TABLE `company` ADD FOREIGN KEY (`role`) REFERENCES `companyRole` (`code`) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE `person` ADD FOREIGN KEY (`title`) REFERENCES `personTitle` (`code`) ON UPDATE SET NULL ON DELETE SET NULL;

ALTER TABLE `person` ADD FOREIGN KEY (`contact`) REFERENCES `contact` (`id`) ON UPDATE SET NULL ON DELETE SET NULL;

ALTER TABLE `companyContact` ADD FOREIGN KEY (`company`) REFERENCES `company` (`id`) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE `companyContact` ADD FOREIGN KEY (`person`) REFERENCES `person` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION;

